### ISSUE TITLE
Document use-case for `isAlive`

### ISSUE THREAD

**Issue by Groostav** [zeroturnaround/zt-process-killer#15]
Hey guys,

I'm wrapping your work for kotlin in [`koxlinx.exec`](https://github.com/groostav/kotlinx.exec), and I'm really not sure what the `isAlive` polling method is useful for. 

Can java's own `Process` become a 'zombie' in the sense that it somehow still exists and `waitFor` isn't returning even though the process doesn't exist anymore? Does it infact discover processes that do exist but are permanently in some non-running state I'm not familiar with?

Can you add something to the documentation to describe when you might want to use `isAlive`, and how?

Cheers 🍻

**Comment by reinra** [comment]
Hi Geoff,

Why isAlive()?

1. `java.lang.Process.isAlive()` was added in Java 8 so our library backports this for older Java versions.

2. `org.zeroturnaround.process.SystemProcess` is not only for processes spawned from the current JVM but also for other system processes. isAlive() check is often used on application startup to check whether the same application is already running via its PID read from a file.

3. If you had only `waitFor()` without `isAlive()` you wouldn't be able to do the check without potentially blocking your thread - a really bad API. `java.lang.Process` has `exitValue()` but in our library we can't provide this for all system processes.

In general `waitFor()` finishes as soon as `isAlive()` would become `false`.

Regards

**Comment by Groostav** [comment]
Ahh, I hadn't noticed the `@since java 1.8`, on `java.lang.Process.isAlive()`. It's surprising that [`java.lang.Process` ever existed without this functionality](https://bugs.java.com/view_bug.do?bug_id=4244896).

That clears things up enormously: it was added to java 8, and you guys effectively back-ported the functionality to java ~6. Nice work!

//begin tangent:

regarding 

> you wouldn't be able to do the check without potentially blocking your thread - a really bad API. 

Its funny how this has changed. I agree with you completely, but if I had the option I would much rather use a Future or Coroutine or even a basic callback to avoid the question altogether **assuming you can find the thread to invoke such a callback/future/coroutine-resume**, though its telling that java-9 adds its so called "process reaper" for exactly this.
