### ISSUE TITLE
Friendly upgrade request for the latest JNA library

### ISSUE THREAD

**Issue by mat013** [zeroturnaround/zt-process-killer#2]
While trying to use the using GetProcessId in the Kernel32 implementation an AccessViolation was caused, which seems not to happened in all situations, and I have not been able to find a pattern in when this issue occurs.

However it seemed to help to upgrade to the latest version of the JNA i.e. net.java.dev.jna:jna:4.2.2 from the version com.sun.jna:jna:3.0.9, which is currently used.

As the 3.0.9 version seems rather old... perhaps it would be an idea to upgrade to a newer version of the library. 

Thanks in advance

Meang

**Comment by reinra** [comment]
Thanks for reporting it. I'll do it if there are no problems.
