### ISSUE TITLE
I can not figure out how to close any process, for example TaskMgr

### ISSUE THREAD

**Issue by iumag** [zeroturnaround/zt-process-killer#6]
I can not figure out how to close any process, for example TaskMgr

**Comment by reinra** [comment]
Our library only deals with java.lang.Process instances and PIDs.
To kill a process based on its name you can execute "taskkill" directly (see "taskkill /?" for help), e.g. using zt-exec. You can also find a PID of an existing process using "tasklist" or "wmic" command.
